git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "opengl_headers",
    build_file = "@//build_external/opengl_headers:BUILD.opengl_headers.bazel",
    commit = "e8f7cd0e35ac8d6f5667a021ff83d04b1fec41ef",
    remote = "https://github.com/KhronosGroup/OpenGL-Registry.git",
)
