git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "spirv_tools",
    commit = "e39e5c5838bc4b4162c349f2a2e5f163efe5432f",
    remote = "https://github.com/KhronosGroup/SPIRV-Tools.git",
    patches = [
        "//build_external/spirv_tools:bazel9.patch",
    ],
    patch_strip = 1,
)
