git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "vulkan_headers",
    build_file = "@//build_external/vulkan_headers:BUILD.vulkan_headers.bazel",
    commit = "0b7f383797fa7be53ae28213e001ae60668ee511",
    remote = "https://github.com/KhronosGroup/Vulkan-Headers.git",
)
