# Cuttlefish with GPU passthrough will use additional file descriptors on the
# host for Gralloc buffers.
@cvdnetwork soft nofile 524288
@cvdnetwork hard nofile 524288
@cvdnetwork soft rtprio 10
@cvdnetwork hard rtprio 10
