git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "glslang",
    build_file = "@//build_external/glslang:BUILD.glslang.bazel",
    commit = "2cc82463217481bf7f187d4f9f3bdf652de363dd",
    dev_dependency = True,
    remote = "https://github.com/KhronosGroup/glslang.git",
)
