[patch.crates-io]
# this needs to be at parity with MODULE.bazel
audio_streams = { git = "https://chromium.googlesource.com/crosvm/crosvm", rev = "0d750f762c23156132f46979598132de01471355" }
# Keep this at parity with the minijail mirror configured by ensure_bazel_git_mirrors.sh.
minijail = { git = "https://chromium.googlesource.com/chromiumos/platform/minijail", rev = "d2e47c2e9aaaa2b175162c31b6bb8976cc762e1a" }
