git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "mesa",
    build_file = "@//build_external/mesa:BUILD.mesa.bazel",
    commit = "e8617e4ca95fc655b0f13fd115c224d27eba2441",
    remote = "https://gitlab.freedesktop.org/mesa/mesa.git",
)
