git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "swiftshader",
    build_file = "@//build_external/swiftshader:BUILD.swiftshader.bazel",
    commit = "6b8d31709ad185dbd64e80865e830a9dbe8e7559",
    remote = "https://swiftshader.googlesource.com/SwiftShader.git",
    patch_strip = 1,
    patches = ["@//build_external/swiftshader:bazel9.patch"],
)
