#!/bin/sh

set -e

case "$1" in
  configure)
    if ! getent passwd _cutf-operator > /dev/null 2>&1
    then
        # The cvdnetwork group is created by ika-base
        adduser --system --disabled-password --disabled-login --home /var/empty \
                --no-create-home --quiet --force-badname --ingroup cvdnetwork _cutf-operator
    fi
    usermod -a -G video,render _cutf-operator > /dev/null 2>&1 || true
esac

#DEBHELPER#

